name: Pipx Install Action
author: Alfi Maulana
description: Install Python packages using pipx with cache support
branding:
  icon: chevrons-right
  color: black
inputs:
  path:
    description: Path of the directory to create
    required: true
runs:
  using: node20
  main: dist/index.mjs
