name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-workspaces:
    name: Check Workspaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Check Format
        run: yarn workspaces foreach --all --topological run format

      - name: Check Diff
        run: git diff --exit-code HEAD

      - name: Check Lint
        run: yarn workspaces foreach --all --topological run lint
