name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Test Package
        run: yarn test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.1.7
        with:
          path: pipx-install-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Install Packages
        uses: ./pipx-install-action
        with:
          packages: black ruff==0.3.0

      - name: Check Packages
        shell: bash
        run: |
          black --version
          VERSION="$(ruff --version)"
          if [ "$VERSION" != "ruff 0.3.0" ]; then
            echo "Expected 'ruff 0.3.0' but instead got '$VERSION'"
            exit 1
          fi
