name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5.0.0

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Test Package
        run: pnpm test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v5.0.0
        with:
          path: pipx-install-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Install Packages
        uses: ./pipx-install-action
        with:
          packages: black ruff==0.3.0

      - name: Check Packages
        shell: bash
        run: |
          black --version
          VERSION="$(ruff --version)"
          if [ "$VERSION" != "ruff 0.3.0" ]; then
            echo "Expected 'ruff 0.3.0' but instead got '$VERSION'"
            exit 1
          fi
