name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-workspaces:
    name: Check Workspaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Check Format
        run: |
          yarn workspaces foreach --all --topological run format
          git diff --exit-code HEAD

      - name: Check Lint
        run: yarn workspaces foreach --all --topological run lint

  test-workspaces:
    name: Test Workspaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Test Workspaces
        run: yarn workspaces foreach --all --topological run test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          path: pipx-install-action
          sparse-checkout: |
            action.yaml
            dist
          sparse-checkout-cone-mode: false

      - name: Install Packages
        uses: ./pipx-install-action
        with:
          packages: black ruff

      - name: Check Packages
        run: black --version && ruff --version
